### ISSUE TITLE
Add Marker Details

### ISSUE THREAD

**Issue by DomiiBunn** [kinshukdua/LiveActionMap#10]
On each marker create a popup with a reference to its data source.

![image](https://user-images.githubusercontent.com/51760394/155846937-b9717968-9c9f-4342-8579-307b6e2a725d.png)

**Comment by rodrigoborgesdeoliveira** [comment]
@kinshukdua I've done some tests with this. Two points about it:
1. Using `folium.Marker`'s `popup` parameter makes the map generation much slower. Any tips for this?
2. Would it be okay to change the structure of the tweets output a little bit in order to extract the places from the tweets and also the link? I saw the tweet response has an id and a text, and this text always ends with a link, but it is getting removed before writing it to the tweets file. Having the output as something like (per row): id=... link=... tweet=... might make things easier to extract later. It'll also be necessary to change the return from the get_words function to include the tweets associated with those places.

**Comment by kinshukdua** [comment]
@rodrigoborgesdeoliveira 
1. I've heard passing `prefer_canvas` to `True` might make the map generation faster, I'm yet to test it though.
2. Yes, if it helps with adding marker details feel free to change the structure of the tweets file.
